import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";



export const metadata = {
  title: "Trade ",
  description: "Generated by Saugat Baral",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=" text-white"
      >
        <Header/>
        <main className="min-h-screen">{children}
          
        </main>
      </body>
    </html>
  );
}
